apiVersion: v1
kind: Service
metadata:
  name: my-jenkis-service
#  labels:
#    env  : prod
#    owner: DenisAstahov
spec:
  selector:
    project: mirantis   # Selecting PODS with those Labels
  ports:
    - name      : mirantis-jenkins
      protocol  : TCP
      port      : 8080  # Port on Load Balancer
      targetPort: 8080  # Port on POD
  type: NodePort