apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: default
spec:
  storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/


    #kubectl create ns jenkins
    #kubectl apply -f jenkins-volume.yaml
    #sudo chown -R 1000:1000 /data/jenkins-volume/